-- Owner: baseline (all modules)
-- Purpose: Full schema baseline so a fresh environment bootstraps with Flyway alone
--          (prod uses ddl-auto=validate, so entities never create schema there).
-- Generated: pg_dump --schema-only against pgvector/pgvector:0.8.2-pg18-trixie after booting
--            the app with ddl-auto=create + runtime initializers (Spring AI vector_store,
--            catalog product_embeddings). Date: 2026-07-07.
-- Compatibility: Existing databases were baselined at version 0
--                (spring.flyway.baseline-version=0), so Flyway skips V0000 there.
--                Fresh databases run V0000 then subsequent migrations.
-- Rollback: Drop the database. This migration is only for empty schemas.

CREATE EXTENSION IF NOT EXISTS hstore WITH SCHEMA public;

CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA public;

CREATE EXTENSION IF NOT EXISTS vector WITH SCHEMA public;

CREATE TABLE public.account_roles (
    account_id bigint NOT NULL,
    role character varying(30) NOT NULL,
    CONSTRAINT account_roles_role_check CHECK (((role)::text = ANY ((ARRAY['USER'::character varying, 'ADMIN'::character varying, 'MANAGER'::character varying])::text[])))
);

CREATE TABLE public.accounts (
    created_at timestamp(6) without time zone NOT NULL,
    id bigint NOT NULL,
    updated_at timestamp(6) without time zone,
    version bigint NOT NULL,
    provider character varying(30) NOT NULL,
    status character varying(30) NOT NULL,
    nickname character varying(50) NOT NULL,
    username character varying(100) NOT NULL,
    provider_id character varying(150),
    email character varying(255) NOT NULL,
    password character varying(255),
    CONSTRAINT accounts_status_check CHECK (((status)::text = ANY ((ARRAY['ACTIVE'::character varying, 'SUSPENDED'::character varying, 'DELETED'::character varying])::text[])))
);

ALTER TABLE public.accounts ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.accounts_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.collection_jobs (
    collected_count integer NOT NULL,
    finished_at timestamp(6) without time zone,
    id bigint NOT NULL,
    requested_at timestamp(6) without time zone NOT NULL,
    started_at timestamp(6) without time zone,
    tracked_keyword_id bigint,
    source character varying(30) NOT NULL,
    status character varying(30) NOT NULL,
    keyword character varying(100) NOT NULL,
    failure_reason character varying(1000),
    CONSTRAINT collection_jobs_source_check CHECK (((source)::text = ANY ((ARRAY['MOCK'::character varying, 'NAVER'::character varying])::text[]))),
    CONSTRAINT collection_jobs_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'RUNNING'::character varying, 'SUCCESS'::character varying, 'FAILED'::character varying])::text[])))
);

ALTER TABLE public.collection_jobs ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.collection_jobs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.comment_like (
    account_id bigint NOT NULL,
    comment_id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    id bigint NOT NULL,
    modified_at timestamp(6) without time zone NOT NULL,
    created_by character varying(100) NOT NULL,
    modified_by character varying(100) NOT NULL
);

ALTER TABLE public.comment_like ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.comment_like_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.comments (
    account_id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    id bigint NOT NULL,
    like_count bigint NOT NULL,
    modified_at timestamp(6) without time zone NOT NULL,
    parent_id bigint,
    post_id bigint NOT NULL,
    nickname character varying(50) NOT NULL,
    created_by character varying(100) NOT NULL,
    modified_by character varying(100) NOT NULL,
    content character varying(500) NOT NULL
);

ALTER TABLE public.comments ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.comments_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.offers (
    active boolean NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    id bigint NOT NULL,
    product_id bigint NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    source character varying(30) NOT NULL,
    mall_name character varying(100),
    external_product_id character varying(120) NOT NULL,
    title character varying(200) NOT NULL,
    image_url character varying(1000),
    product_url character varying(1000)
);

ALTER TABLE public.offers ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.offers_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.outbox_events (
    retry_count integer NOT NULL,
    available_at timestamp(6) with time zone NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    id bigint NOT NULL,
    occurred_at timestamp(6) with time zone NOT NULL,
    published_at timestamp(6) with time zone,
    updated_at timestamp(6) with time zone NOT NULL,
    status character varying(30) NOT NULL,
    event_id character varying(36) NOT NULL,
    aggregate_type character varying(80),
    aggregate_id character varying(100),
    event_type character varying(150) NOT NULL,
    last_error character varying(2000),
    payload text NOT NULL,
    CONSTRAINT outbox_events_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'PROCESSING'::character varying, 'PUBLISHED'::character varying, 'FAILED'::character varying])::text[])))
);

ALTER TABLE public.outbox_events ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.outbox_events_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.post_file (
    created_at timestamp(6) without time zone NOT NULL,
    file_size bigint,
    id bigint NOT NULL,
    post_id bigint,
    file_type character varying(100) NOT NULL,
    file_path character varying(500) NOT NULL,
    original_file_name character varying(255) NOT NULL,
    saved_file_name character varying(255) NOT NULL
);

ALTER TABLE public.post_file ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.post_file_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.post_like (
    account_id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    id bigint NOT NULL,
    modified_at timestamp(6) without time zone NOT NULL,
    post_id bigint NOT NULL,
    created_by character varying(100) NOT NULL,
    modified_by character varying(100) NOT NULL
);

ALTER TABLE public.post_like ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.post_like_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.post_product_links (
    post_date date NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    id bigint NOT NULL,
    post_id bigint NOT NULL,
    product_id bigint NOT NULL
);

ALTER TABLE public.post_product_links ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.post_product_links_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.post_purchase_vote (
    account_id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    id bigint NOT NULL,
    modified_at timestamp(6) without time zone NOT NULL,
    post_id bigint NOT NULL,
    vote_type character varying(30) NOT NULL,
    created_by character varying(100) NOT NULL,
    modified_by character varying(100) NOT NULL,
    CONSTRAINT post_purchase_vote_vote_type_check CHECK (((vote_type)::text = ANY ((ARRAY['BUYABLE'::character varying, 'UNSURE'::character varying, 'WAIT'::character varying])::text[])))
);

ALTER TABLE public.post_purchase_vote ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.post_purchase_vote_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.post_reference_links (
    id bigint NOT NULL,
    post_id bigint NOT NULL,
    product_id bigint,
    published_at timestamp(6) without time zone,
    provider character varying(30) NOT NULL,
    publish_origin character varying(30) NOT NULL,
    keyword character varying(100) NOT NULL,
    source_name character varying(100) NOT NULL,
    title_snapshot character varying(500) NOT NULL,
    canonical_url character varying(1000) NOT NULL,
    original_url character varying(1000) NOT NULL,
    CONSTRAINT post_reference_links_provider_check CHECK (((provider)::text = 'NAVER_NEWS'::text)),
    CONSTRAINT post_reference_links_publish_origin_check CHECK (((publish_origin)::text = ANY ((ARRAY['USER'::character varying, 'SYSTEM_BATCH'::character varying, 'ADMIN_BACKFILL'::character varying])::text[])))
);

ALTER TABLE public.post_reference_links ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.post_reference_links_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.post_tags (
    post_id bigint NOT NULL,
    tag character varying(50)
);

CREATE TABLE public.posts (
    account_id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    id bigint NOT NULL,
    like_count bigint NOT NULL,
    modified_at timestamp(6) without time zone NOT NULL,
    views bigint NOT NULL,
    board_category character varying(30) NOT NULL,
    category character varying(30) NOT NULL,
    publish_origin character varying(30) NOT NULL,
    nickname character varying(50) NOT NULL,
    created_by character varying(100) NOT NULL,
    modified_by character varying(100) NOT NULL,
    title character varying(100) NOT NULL,
    summary character varying(500),
    content character varying(10000) NOT NULL,
    CONSTRAINT posts_board_category_check CHECK (((board_category)::text = ANY ((ARRAY['GENERAL'::character varying, 'DIGITAL'::character varying, 'APPLIANCE'::character varying, 'LIVING'::character varying, 'HEALTH'::character varying, 'BEAUTY'::character varying, 'SPORTS'::character varying])::text[]))),
    CONSTRAINT posts_category_check CHECK (((category)::text = ANY ((ARRAY['GENERAL'::character varying, 'AI_ANALYSIS'::character varying, 'PRODUCT_LAUNCH_NEWS'::character varying])::text[]))),
    CONSTRAINT posts_publish_origin_check CHECK (((publish_origin)::text = ANY ((ARRAY['USER'::character varying, 'SYSTEM_BATCH'::character varying, 'ADMIN_BACKFILL'::character varying])::text[])))
);

ALTER TABLE public.posts ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.posts_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.price_snapshots (
    collected_at timestamp(6) without time zone NOT NULL,
    id bigint NOT NULL,
    offer_id bigint NOT NULL,
    price bigint NOT NULL,
    product_id bigint NOT NULL,
    source character varying(30) NOT NULL,
    external_product_id character varying(120) NOT NULL
);

ALTER TABLE public.price_snapshots ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.price_snapshots_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.product_categories (
    depth integer NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    id bigint NOT NULL,
    parent_id bigint,
    updated_at timestamp(6) without time zone NOT NULL,
    name character varying(100) NOT NULL
);

ALTER TABLE public.product_categories ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.product_categories_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.product_embeddings (
    product_id bigint NOT NULL,
    embedding_input text NOT NULL,
    embedding public.vector(1536) NOT NULL,
    created_at timestamp without time zone NOT NULL,
    updated_at timestamp without time zone NOT NULL
);

CREATE TABLE public.product_match_candidates (
    brand_matched boolean NOT NULL,
    category_matched boolean NOT NULL,
    similarity_score numeric(6,4) NOT NULL,
    candidate_product_id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    id bigint NOT NULL,
    source_product_id bigint NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    source character varying(30) NOT NULL,
    status character varying(30) NOT NULL,
    external_product_id character varying(120) NOT NULL,
    source_product_title character varying(200) NOT NULL,
    CONSTRAINT product_match_candidates_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'APPROVED'::character varying, 'REJECTED'::character varying])::text[])))
);

ALTER TABLE public.product_match_candidates ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.product_match_candidates_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.products (
    category_id bigint,
    created_at timestamp(6) without time zone NOT NULL,
    current_price bigint NOT NULL,
    id bigint NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    source character varying(30) NOT NULL,
    status character varying(30) NOT NULL,
    brand character varying(100),
    category1 character varying(100),
    category2 character varying(100),
    category3 character varying(100),
    maker character varying(100),
    mall_name character varying(100),
    external_product_id character varying(120) NOT NULL,
    name character varying(200) NOT NULL,
    normalized_name character varying(200) NOT NULL,
    image_url character varying(1000),
    product_url character varying(1000),
    CONSTRAINT products_status_check CHECK (((status)::text = ANY ((ARRAY['ACTIVE'::character varying, 'HIDDEN'::character varying])::text[])))
);

ALTER TABLE public.products ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.products_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.raw_products (
    collected_at timestamp(6) without time zone NOT NULL,
    collection_job_id bigint NOT NULL,
    id bigint NOT NULL,
    source character varying(30) NOT NULL,
    external_product_id character varying(120) NOT NULL,
    raw_payload text NOT NULL,
    CONSTRAINT raw_products_source_check CHECK (((source)::text = ANY ((ARRAY['MOCK'::character varying, 'NAVER'::character varying])::text[])))
);

ALTER TABLE public.raw_products ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.raw_products_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.tracked_keywords (
    display_count integer NOT NULL,
    enabled boolean NOT NULL,
    interval_minutes integer NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    id bigint NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    source character varying(30) NOT NULL,
    keyword character varying(100) NOT NULL,
    CONSTRAINT tracked_keywords_source_check CHECK (((source)::text = ANY ((ARRAY['MOCK'::character varying, 'NAVER'::character varying])::text[])))
);

ALTER TABLE public.tracked_keywords ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tracked_keywords_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.vector_store (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    content text,
    metadata json,
    embedding public.vector(1536)
);

ALTER TABLE ONLY public.accounts
    ADD CONSTRAINT accounts_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.collection_jobs
    ADD CONSTRAINT collection_jobs_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.comment_like
    ADD CONSTRAINT comment_like_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.comments
    ADD CONSTRAINT comments_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.offers
    ADD CONSTRAINT offers_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.outbox_events
    ADD CONSTRAINT outbox_events_event_id_key UNIQUE (event_id);

ALTER TABLE ONLY public.outbox_events
    ADD CONSTRAINT outbox_events_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.post_file
    ADD CONSTRAINT post_file_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.post_like
    ADD CONSTRAINT post_like_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.post_product_links
    ADD CONSTRAINT post_product_links_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.post_purchase_vote
    ADD CONSTRAINT post_purchase_vote_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.post_reference_links
    ADD CONSTRAINT post_reference_links_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.posts
    ADD CONSTRAINT posts_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.price_snapshots
    ADD CONSTRAINT price_snapshots_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.product_categories
    ADD CONSTRAINT product_categories_name_key UNIQUE (name);

ALTER TABLE ONLY public.product_categories
    ADD CONSTRAINT product_categories_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.product_embeddings
    ADD CONSTRAINT product_embeddings_pkey PRIMARY KEY (product_id);

ALTER TABLE ONLY public.product_match_candidates
    ADD CONSTRAINT product_match_candidates_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.products
    ADD CONSTRAINT products_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.raw_products
    ADD CONSTRAINT raw_products_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.tracked_keywords
    ADD CONSTRAINT tracked_keywords_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.account_roles
    ADD CONSTRAINT uk_account_roles_account_role PRIMARY KEY (account_id, role);

ALTER TABLE ONLY public.accounts
    ADD CONSTRAINT uk_accounts_email UNIQUE (email);

ALTER TABLE ONLY public.accounts
    ADD CONSTRAINT uk_accounts_nickname UNIQUE (nickname);

ALTER TABLE ONLY public.accounts
    ADD CONSTRAINT uk_accounts_provider_provider_id UNIQUE (provider, provider_id);

ALTER TABLE ONLY public.accounts
    ADD CONSTRAINT uk_accounts_username UNIQUE (username);

ALTER TABLE ONLY public.comment_like
    ADD CONSTRAINT uk_comment_like_comment_account UNIQUE (comment_id, account_id);

ALTER TABLE ONLY public.offers
    ADD CONSTRAINT uk_offers_source_external_product_id UNIQUE (source, external_product_id);

ALTER TABLE ONLY public.post_like
    ADD CONSTRAINT uk_post_like_post_account UNIQUE (post_id, account_id);

ALTER TABLE ONLY public.post_product_links
    ADD CONSTRAINT uk_post_product_links_post_id UNIQUE (post_id);

ALTER TABLE ONLY public.post_product_links
    ADD CONSTRAINT uk_post_product_links_product_post_date UNIQUE (product_id, post_date);

ALTER TABLE ONLY public.post_purchase_vote
    ADD CONSTRAINT uk_post_purchase_vote_post_account UNIQUE (post_id, account_id);

ALTER TABLE ONLY public.post_reference_links
    ADD CONSTRAINT uk_post_reference_links_canonical_url UNIQUE (canonical_url);

ALTER TABLE ONLY public.product_match_candidates
    ADD CONSTRAINT uk_product_match_candidates_source_candidate_status UNIQUE (source_product_id, candidate_product_id, status);

ALTER TABLE ONLY public.products
    ADD CONSTRAINT uk_products_source_external_id UNIQUE (source, external_product_id);

ALTER TABLE ONLY public.tracked_keywords
    ADD CONSTRAINT uk_tracked_keywords_source_keyword UNIQUE (source, keyword);

ALTER TABLE ONLY public.vector_store
    ADD CONSTRAINT vector_store_pkey PRIMARY KEY (id);

CREATE INDEX idx_accounts_status ON public.accounts USING btree (status);

CREATE INDEX idx_comment_like_account_comment ON public.comment_like USING btree (account_id, comment_id);

CREATE INDEX idx_comments_parent_id ON public.comments USING btree (parent_id);

CREATE INDEX idx_comments_post_created_at ON public.comments USING btree (post_id, created_at);

CREATE INDEX idx_offers_product_id ON public.offers USING btree (product_id);

CREATE INDEX idx_outbox_events_aggregate ON public.outbox_events USING btree (aggregate_type, aggregate_id);

CREATE INDEX idx_outbox_events_event_type_created_at ON public.outbox_events USING btree (event_type, created_at);

CREATE INDEX idx_outbox_events_status_available_at ON public.outbox_events USING btree (status, available_at);

CREATE INDEX idx_post_file_post_created_at ON public.post_file USING btree (post_id, created_at);

CREATE INDEX idx_post_like_account_post ON public.post_like USING btree (account_id, post_id);

CREATE INDEX idx_post_product_links_product_id ON public.post_product_links USING btree (product_id);

CREATE INDEX idx_post_purchase_vote_account_post ON public.post_purchase_vote USING btree (account_id, post_id);

CREATE INDEX idx_post_purchase_vote_post_id ON public.post_purchase_vote USING btree (post_id);

CREATE INDEX idx_post_reference_links_post_id ON public.post_reference_links USING btree (post_id);

CREATE INDEX idx_post_reference_links_provider ON public.post_reference_links USING btree (provider);

CREATE INDEX idx_post_tags_post_id ON public.post_tags USING btree (post_id);

CREATE INDEX idx_posts_account_id ON public.posts USING btree (account_id);

CREATE INDEX idx_posts_board_category ON public.posts USING btree (board_category);

CREATE INDEX idx_posts_category ON public.posts USING btree (category);

CREATE INDEX idx_posts_created_at ON public.posts USING btree (created_at);

CREATE INDEX idx_posts_publish_origin ON public.posts USING btree (publish_origin);

CREATE INDEX idx_price_snapshots_offer_collected ON public.price_snapshots USING btree (offer_id, collected_at);

CREATE INDEX idx_price_snapshots_product_collected ON public.price_snapshots USING btree (product_id, collected_at);

CREATE INDEX idx_price_snapshots_source_external ON public.price_snapshots USING btree (source, external_product_id);

CREATE INDEX idx_product_embeddings_embedding ON public.product_embeddings USING hnsw (embedding public.vector_cosine_ops);

CREATE INDEX idx_product_match_candidates_candidate ON public.product_match_candidates USING btree (candidate_product_id);

CREATE INDEX idx_product_match_candidates_status_created ON public.product_match_candidates USING btree (status, created_at);

CREATE INDEX idx_products_category_id ON public.products USING btree (category_id);

CREATE INDEX idx_products_normalized_name ON public.products USING btree (normalized_name);

CREATE INDEX idx_products_status_created_at ON public.products USING btree (status, created_at);

CREATE INDEX spring_ai_vector_index ON public.vector_store USING hnsw (embedding public.vector_cosine_ops);

ALTER TABLE ONLY public.account_roles
    ADD CONSTRAINT fk61h48dsir3h82pxbq3cwgp0ce FOREIGN KEY (account_id) REFERENCES public.accounts(id);

ALTER TABLE ONLY public.products
    ADD CONSTRAINT fk6t5dtw6tyo83ywljwohuc6g7k FOREIGN KEY (category_id) REFERENCES public.product_categories(id);

ALTER TABLE ONLY public.post_reference_links
    ADD CONSTRAINT fkanh041l5gmwvo5icwdje66yxk FOREIGN KEY (post_id) REFERENCES public.posts(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.post_like
    ADD CONSTRAINT fkcf8kqsucxsmplv3xw9gubrql0 FOREIGN KEY (post_id) REFERENCES public.posts(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.post_purchase_vote
    ADD CONSTRAINT fkf3o2eqj3kia0l026ip4mqi9wt FOREIGN KEY (post_id) REFERENCES public.posts(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.comments
    ADD CONSTRAINT fkh4c7lvsc298whoyd4w9ta25cr FOREIGN KEY (post_id) REFERENCES public.posts(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.offers
    ADD CONSTRAINT fkjf1jh3h4v4m7diel8vvhmuqas FOREIGN KEY (product_id) REFERENCES public.products(id);

ALTER TABLE ONLY public.post_file
    ADD CONSTRAINT fkk08pgr1gtb7sg0dpsh6pdinc FOREIGN KEY (post_id) REFERENCES public.posts(id);

ALTER TABLE ONLY public.post_tags
    ADD CONSTRAINT fkkifam22p4s1nm3bkmp1igcn5w FOREIGN KEY (post_id) REFERENCES public.posts(id);

ALTER TABLE ONLY public.comment_like
    ADD CONSTRAINT fkl1mu2ryf4k4ps93b5b52q2m8i FOREIGN KEY (comment_id) REFERENCES public.comments(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.comments
    ADD CONSTRAINT fklri30okf66phtcgbe5pok7cc0 FOREIGN KEY (parent_id) REFERENCES public.comments(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.raw_products
    ADD CONSTRAINT fkollw1ocg2cwu4jl94p037lv8a FOREIGN KEY (collection_job_id) REFERENCES public.collection_jobs(id);

ALTER TABLE ONLY public.post_product_links
    ADD CONSTRAINT fks5dr0lu9bg8j1olhn5xu7wi8k FOREIGN KEY (post_id) REFERENCES public.posts(id);
