app:
  token:
    secret-key: asdfasdfsadfasdf
    expiration:
      access-token: 864000
      refresh-token: 3000000
spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        show_sql: true
    open-in-view: false
  datasource:
    url: jdbc:mysql://mysql:3306/login?serverTimezone=Asia/Seoul&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 12345678
