-- Owner: app
-- Purpose: 재베이스라인(2차). 뉴스 도메인을 떠나는 시점(ADR-007)을 새 출발로 보고, 이전 이력
--          V0000(2026-08-21 baseline)~V0003(GOOGLE_NEWS provider)을 단일 baseline으로 교체한다.
--          2026-09-30 기준 postforge_google DB(V0000~V0003 적용본)에서 pg_dump --schema-only로 뽑았다.
--          2026-10-02(ADR-008 뉴스 퇴역): post_reference_links 표, posts의 summary·category·board_category·
--          publish_origin 열과 그 CHECK·인덱스, 뉴스봇 계정(id 0) 시드를 뺐다. RAG를 지워 vector_store와
--          hstore·uuid-ossp·vector 확장도 뺐다. 첨부파일(S3)을 지워 post_file도 뺐다.
-- Tables: accounts, account_roles, posts, post_tags, comments, comment_like, post_like
-- Compatibility: 신규 DB 전용. 기존 DB(옛 이력 적용본)는 DB를 지우고 다시 만든다 — 뉴스 게시글·벡터 데이터는
--                ADR-007·ADR-008에 따라 폐기 대상이고, 계정은 재가입 또는 accounts·account_roles 덤프로 옮긴다.
-- Rollback: 이전 이력은 git 커밋 0be32ca5 이전에 보존된다.
-- Verification: 빈 DB에 이 파일 하나가 적용된 뒤 Hibernate ddl-auto=validate가 전 엔티티를 통과한다.

--
-- PostgreSQL database dump
--


-- Dumped from database version 18.3 (Debian 18.3-1.pgdg13+1)
-- Dumped by pg_dump version 18.3 (Debian 18.3-1.pgdg13+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: account_roles; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.account_roles (
    account_id bigint NOT NULL,
    role character varying(30) NOT NULL,
    CONSTRAINT account_roles_role_check CHECK (((role)::text = ANY (ARRAY[('USER'::character varying)::text, ('ADMIN'::character varying)::text, ('MANAGER'::character varying)::text])))
);


--
-- Name: accounts; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.accounts (
    created_at timestamp(6) without time zone NOT NULL,
    id bigint NOT NULL,
    updated_at timestamp(6) without time zone,
    version bigint NOT NULL,
    provider character varying(30) NOT NULL,
    status character varying(30) NOT NULL,
    nickname character varying(50) NOT NULL,
    username character varying(100) NOT NULL,
    provider_id character varying(150),
    email character varying(255) NOT NULL,
    password character varying(255),
    CONSTRAINT accounts_status_check CHECK (((status)::text = ANY (ARRAY[('ACTIVE'::character varying)::text, ('SUSPENDED'::character varying)::text, ('DELETED'::character varying)::text])))
);


--
-- Name: accounts_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.accounts ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.accounts_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: comment_like; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.comment_like (
    account_id bigint NOT NULL,
    comment_id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    id bigint NOT NULL,
    modified_at timestamp(6) without time zone NOT NULL,
    created_by character varying(100) NOT NULL,
    modified_by character varying(100) NOT NULL
);


--
-- Name: comment_like_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.comment_like ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.comment_like_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: comments; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.comments (
    account_id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    id bigint NOT NULL,
    like_count bigint NOT NULL,
    modified_at timestamp(6) without time zone NOT NULL,
    parent_id bigint,
    post_id bigint NOT NULL,
    nickname character varying(50) NOT NULL,
    created_by character varying(100) NOT NULL,
    modified_by character varying(100) NOT NULL,
    content character varying(500) NOT NULL
);


--
-- Name: comments_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.comments ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.comments_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: post_like; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.post_like (
    account_id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    id bigint NOT NULL,
    modified_at timestamp(6) without time zone NOT NULL,
    post_id bigint NOT NULL,
    created_by character varying(100) NOT NULL,
    modified_by character varying(100) NOT NULL
);


--
-- Name: post_like_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.post_like ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.post_like_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: post_tags; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.post_tags (
    post_id bigint NOT NULL,
    tag character varying(50)
);


--
-- Name: posts; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.posts (
    account_id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    id bigint NOT NULL,
    like_count bigint NOT NULL,
    modified_at timestamp(6) without time zone NOT NULL,
    views bigint NOT NULL,
    nickname character varying(50) NOT NULL,
    created_by character varying(100) NOT NULL,
    modified_by character varying(100) NOT NULL,
    title character varying(100) NOT NULL,
    content character varying(10000) NOT NULL
);


--
-- Name: posts_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.posts ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.posts_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: accounts accounts_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.accounts
    ADD CONSTRAINT accounts_pkey PRIMARY KEY (id);


--
-- Name: comment_like comment_like_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.comment_like
    ADD CONSTRAINT comment_like_pkey PRIMARY KEY (id);


--
-- Name: comments comments_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.comments
    ADD CONSTRAINT comments_pkey PRIMARY KEY (id);


--
-- Name: post_like post_like_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.post_like
    ADD CONSTRAINT post_like_pkey PRIMARY KEY (id);


--
-- Name: posts posts_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.posts
    ADD CONSTRAINT posts_pkey PRIMARY KEY (id);


--
-- Name: account_roles uk_account_roles_account_role; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.account_roles
    ADD CONSTRAINT uk_account_roles_account_role PRIMARY KEY (account_id, role);


--
-- Name: accounts uk_accounts_email; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.accounts
    ADD CONSTRAINT uk_accounts_email UNIQUE (email);


--
-- Name: accounts uk_accounts_nickname; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.accounts
    ADD CONSTRAINT uk_accounts_nickname UNIQUE (nickname);


--
-- Name: accounts uk_accounts_provider_provider_id; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.accounts
    ADD CONSTRAINT uk_accounts_provider_provider_id UNIQUE (provider, provider_id);


--
-- Name: accounts uk_accounts_username; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.accounts
    ADD CONSTRAINT uk_accounts_username UNIQUE (username);


--
-- Name: comment_like uk_comment_like_comment_account; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.comment_like
    ADD CONSTRAINT uk_comment_like_comment_account UNIQUE (comment_id, account_id);


--
-- Name: post_like uk_post_like_post_account; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.post_like
    ADD CONSTRAINT uk_post_like_post_account UNIQUE (post_id, account_id);


--
-- Name: idx_accounts_status; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_accounts_status ON public.accounts USING btree (status);


--
-- Name: idx_comment_like_account_comment; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_comment_like_account_comment ON public.comment_like USING btree (account_id, comment_id);


--
-- Name: idx_comments_parent_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_comments_parent_id ON public.comments USING btree (parent_id);


--
-- Name: idx_comments_post_created_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_comments_post_created_at ON public.comments USING btree (post_id, created_at);


--
-- Name: idx_post_like_account_post; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_post_like_account_post ON public.post_like USING btree (account_id, post_id);


--
-- Name: idx_post_tags_post_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_post_tags_post_id ON public.post_tags USING btree (post_id);


--
-- Name: idx_posts_account_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_posts_account_id ON public.posts USING btree (account_id);


--
-- Name: idx_posts_created_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_posts_created_at ON public.posts USING btree (created_at);


--
-- Name: account_roles fk61h48dsir3h82pxbq3cwgp0ce; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.account_roles
    ADD CONSTRAINT fk61h48dsir3h82pxbq3cwgp0ce FOREIGN KEY (account_id) REFERENCES public.accounts(id);


--
-- Name: comment_like fk_comment_like_account; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.comment_like
    ADD CONSTRAINT fk_comment_like_account FOREIGN KEY (account_id) REFERENCES public.accounts(id);


--
-- Name: comments fk_comments_account; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.comments
    ADD CONSTRAINT fk_comments_account FOREIGN KEY (account_id) REFERENCES public.accounts(id);


--
-- Name: post_like fk_post_like_account; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.post_like
    ADD CONSTRAINT fk_post_like_account FOREIGN KEY (account_id) REFERENCES public.accounts(id);


--
-- Name: posts fk_posts_account; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.posts
    ADD CONSTRAINT fk_posts_account FOREIGN KEY (account_id) REFERENCES public.accounts(id);


--
-- Name: post_like fkcf8kqsucxsmplv3xw9gubrql0; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.post_like
    ADD CONSTRAINT fkcf8kqsucxsmplv3xw9gubrql0 FOREIGN KEY (post_id) REFERENCES public.posts(id) ON DELETE CASCADE;


--
-- Name: comments fkh4c7lvsc298whoyd4w9ta25cr; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.comments
    ADD CONSTRAINT fkh4c7lvsc298whoyd4w9ta25cr FOREIGN KEY (post_id) REFERENCES public.posts(id) ON DELETE CASCADE;


--
-- Name: post_tags fkkifam22p4s1nm3bkmp1igcn5w; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.post_tags
    ADD CONSTRAINT fkkifam22p4s1nm3bkmp1igcn5w FOREIGN KEY (post_id) REFERENCES public.posts(id);


--
-- Name: comment_like fkl1mu2ryf4k4ps93b5b52q2m8i; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.comment_like
    ADD CONSTRAINT fkl1mu2ryf4k4ps93b5b52q2m8i FOREIGN KEY (comment_id) REFERENCES public.comments(id) ON DELETE CASCADE;


--
-- Name: comments fklri30okf66phtcgbe5pok7cc0; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.comments
    ADD CONSTRAINT fklri30okf66phtcgbe5pok7cc0 FOREIGN KEY (parent_id) REFERENCES public.comments(id) ON DELETE CASCADE;


--
-- PostgreSQL database dump complete
--

