-- Owner: app
-- Purpose: 재베이스라인. ADR-005로 방향이 확정되며 이전 이력(V0000~V0007)이 만들었다 지우는
--          왕복(가격 테이블 11개 생성→드롭, board_category 추가→드롭→부활)만 남겨 단일 baseline으로 교체한다.
--          ADR-004가 예고한 절차("컷 이후 스키마에서 pg_dump로 다시 뽑는다")의 실행이다.
-- Tables: accounts, account_roles, posts, post_tags, comments, comment_like, post_like,
--         post_file, post_reference_links, tracked_keywords, vector_store
-- Compatibility: 신규 DB 전용. 기존 DB(옛 이력 적용본)는 볼륨을 비우고 재생성한다 — 2026-08-21 기준
--                V0005+가 배포된 환경이 없고 prod 데이터 폐기가 확인되어 안전하다.
-- Rollback: 이전 이력은 git 태그 pre-scope-cut 및 그 이후 커밋에 보존된다.
-- Verification: 빈 DB에 이 파일 하나가 적용된 뒤 Hibernate ddl-auto=validate가 전 엔티티를 통과한다.

--
-- PostgreSQL database dump
--

--
-- Name: hstore; Type: EXTENSION; Schema: -; Owner: -
--

CREATE EXTENSION IF NOT EXISTS hstore WITH SCHEMA public;

--
-- Name: EXTENSION hstore; Type: COMMENT; Schema: -; Owner: -
--

COMMENT ON EXTENSION hstore IS 'data type for storing sets of (key, value) pairs';

--
-- Name: uuid-ossp; Type: EXTENSION; Schema: -; Owner: -
--

CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA public;

--
-- Name: EXTENSION "uuid-ossp"; Type: COMMENT; Schema: -; Owner: -
--

COMMENT ON EXTENSION "uuid-ossp" IS 'generate universally unique identifiers (UUIDs)';

--
-- Name: vector; Type: EXTENSION; Schema: -; Owner: -
--

CREATE EXTENSION IF NOT EXISTS vector WITH SCHEMA public;

--
-- Name: EXTENSION vector; Type: COMMENT; Schema: -; Owner: -
--

COMMENT ON EXTENSION vector IS 'vector data type and ivfflat and hnsw access methods';

--
-- Name: account_roles; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.account_roles (
    account_id bigint NOT NULL,
    role character varying(30) NOT NULL,
    CONSTRAINT account_roles_role_check CHECK (((role)::text = ANY (ARRAY[('USER'::character varying)::text, ('ADMIN'::character varying)::text, ('MANAGER'::character varying)::text])))
);

--
-- Name: accounts; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.accounts (
    created_at timestamp(6) without time zone NOT NULL,
    id bigint NOT NULL,
    updated_at timestamp(6) without time zone,
    version bigint NOT NULL,
    provider character varying(30) NOT NULL,
    status character varying(30) NOT NULL,
    nickname character varying(50) NOT NULL,
    username character varying(100) NOT NULL,
    provider_id character varying(150),
    email character varying(255) NOT NULL,
    password character varying(255),
    CONSTRAINT accounts_status_check CHECK (((status)::text = ANY (ARRAY[('ACTIVE'::character varying)::text, ('SUSPENDED'::character varying)::text, ('DELETED'::character varying)::text])))
);

--
-- Name: accounts_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.accounts ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.accounts_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: comment_like; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.comment_like (
    account_id bigint NOT NULL,
    comment_id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    id bigint NOT NULL,
    modified_at timestamp(6) without time zone NOT NULL,
    created_by character varying(100) NOT NULL,
    modified_by character varying(100) NOT NULL
);

--
-- Name: comment_like_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.comment_like ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.comment_like_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: comments; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.comments (
    account_id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    id bigint NOT NULL,
    like_count bigint NOT NULL,
    modified_at timestamp(6) without time zone NOT NULL,
    parent_id bigint,
    post_id bigint NOT NULL,
    nickname character varying(50) NOT NULL,
    created_by character varying(100) NOT NULL,
    modified_by character varying(100) NOT NULL,
    content character varying(500) NOT NULL
);

--
-- Name: comments_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.comments ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.comments_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: post_file; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.post_file (
    created_at timestamp(6) without time zone NOT NULL,
    file_size bigint,
    id bigint NOT NULL,
    post_id bigint,
    file_type character varying(100) NOT NULL,
    file_path character varying(500) NOT NULL,
    original_file_name character varying(255) NOT NULL,
    saved_file_name character varying(255) NOT NULL
);

--
-- Name: post_file_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.post_file ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.post_file_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: post_like; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.post_like (
    account_id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    id bigint NOT NULL,
    modified_at timestamp(6) without time zone NOT NULL,
    post_id bigint NOT NULL,
    created_by character varying(100) NOT NULL,
    modified_by character varying(100) NOT NULL
);

--
-- Name: post_like_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.post_like ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.post_like_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: post_reference_links; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.post_reference_links (
    id bigint NOT NULL,
    post_id bigint NOT NULL,
    published_at timestamp(6) without time zone,
    provider character varying(30) NOT NULL,
    publish_origin character varying(30) NOT NULL,
    keyword character varying(100) NOT NULL,
    source_name character varying(100) NOT NULL,
    title_snapshot character varying(500) NOT NULL,
    canonical_url character varying(1000) NOT NULL,
    original_url character varying(1000) NOT NULL,
    CONSTRAINT post_reference_links_provider_check CHECK (((provider)::text = 'NAVER_NEWS'::text)),
    CONSTRAINT post_reference_links_publish_origin_check CHECK (((publish_origin)::text = ANY (ARRAY[('USER'::character varying)::text, ('SYSTEM_BATCH'::character varying)::text, ('ADMIN_BACKFILL'::character varying)::text])))
);

--
-- Name: post_reference_links_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.post_reference_links ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.post_reference_links_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: post_tags; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.post_tags (
    post_id bigint NOT NULL,
    tag character varying(50)
);

--
-- Name: posts; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.posts (
    account_id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    id bigint NOT NULL,
    like_count bigint NOT NULL,
    modified_at timestamp(6) without time zone NOT NULL,
    views bigint NOT NULL,
    category character varying(30) NOT NULL,
    publish_origin character varying(30) NOT NULL,
    nickname character varying(50) NOT NULL,
    created_by character varying(100) NOT NULL,
    modified_by character varying(100) NOT NULL,
    title character varying(100) NOT NULL,
    summary character varying(500),
    content character varying(10000) NOT NULL,
    board_category character varying(30) DEFAULT 'GENERAL'::character varying NOT NULL,
    CONSTRAINT posts_board_category_check CHECK (((board_category)::text = ANY ((ARRAY['GENERAL'::character varying, 'DIGITAL'::character varying, 'APPLIANCE'::character varying, 'LIVING'::character varying, 'HEALTH'::character varying, 'BEAUTY'::character varying, 'SPORTS'::character varying])::text[]))),
    CONSTRAINT posts_category_check CHECK (((category)::text = ANY ((ARRAY['GENERAL'::character varying, 'DAILY_DIGEST'::character varying, 'PRODUCT_LAUNCH_NEWS'::character varying])::text[]))),
    CONSTRAINT posts_publish_origin_check CHECK (((publish_origin)::text = ANY (ARRAY[('USER'::character varying)::text, ('SYSTEM_BATCH'::character varying)::text, ('ADMIN_BACKFILL'::character varying)::text])))
);

--
-- Name: posts_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.posts ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.posts_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: tracked_keywords; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tracked_keywords (
    display_count integer NOT NULL,
    enabled boolean NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    id bigint NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    keyword character varying(100) NOT NULL,
    category character varying(30) DEFAULT 'GENERAL'::character varying NOT NULL,
    CONSTRAINT tracked_keywords_category_check CHECK (((category)::text = ANY ((ARRAY['GENERAL'::character varying, 'DIGITAL'::character varying, 'APPLIANCE'::character varying, 'LIVING'::character varying, 'HEALTH'::character varying, 'BEAUTY'::character varying, 'SPORTS'::character varying])::text[])))
);

--
-- Name: tracked_keywords_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.tracked_keywords ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tracked_keywords_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: vector_store; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.vector_store (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    content text,
    metadata json,
    embedding public.vector(1536)
);

--
-- Name: accounts accounts_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.accounts
    ADD CONSTRAINT accounts_pkey PRIMARY KEY (id);

--
-- Name: comment_like comment_like_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.comment_like
    ADD CONSTRAINT comment_like_pkey PRIMARY KEY (id);

--
-- Name: comments comments_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.comments
    ADD CONSTRAINT comments_pkey PRIMARY KEY (id);

--
-- Name: post_file post_file_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.post_file
    ADD CONSTRAINT post_file_pkey PRIMARY KEY (id);

--
-- Name: post_like post_like_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.post_like
    ADD CONSTRAINT post_like_pkey PRIMARY KEY (id);

--
-- Name: post_reference_links post_reference_links_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.post_reference_links
    ADD CONSTRAINT post_reference_links_pkey PRIMARY KEY (id);

--
-- Name: posts posts_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.posts
    ADD CONSTRAINT posts_pkey PRIMARY KEY (id);

--
-- Name: tracked_keywords tracked_keywords_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tracked_keywords
    ADD CONSTRAINT tracked_keywords_pkey PRIMARY KEY (id);

--
-- Name: account_roles uk_account_roles_account_role; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.account_roles
    ADD CONSTRAINT uk_account_roles_account_role PRIMARY KEY (account_id, role);

--
-- Name: accounts uk_accounts_email; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.accounts
    ADD CONSTRAINT uk_accounts_email UNIQUE (email);

--
-- Name: accounts uk_accounts_nickname; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.accounts
    ADD CONSTRAINT uk_accounts_nickname UNIQUE (nickname);

--
-- Name: accounts uk_accounts_provider_provider_id; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.accounts
    ADD CONSTRAINT uk_accounts_provider_provider_id UNIQUE (provider, provider_id);

--
-- Name: accounts uk_accounts_username; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.accounts
    ADD CONSTRAINT uk_accounts_username UNIQUE (username);

--
-- Name: comment_like uk_comment_like_comment_account; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.comment_like
    ADD CONSTRAINT uk_comment_like_comment_account UNIQUE (comment_id, account_id);

--
-- Name: post_like uk_post_like_post_account; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.post_like
    ADD CONSTRAINT uk_post_like_post_account UNIQUE (post_id, account_id);

--
-- Name: post_reference_links uk_post_reference_links_canonical_url; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.post_reference_links
    ADD CONSTRAINT uk_post_reference_links_canonical_url UNIQUE (canonical_url);

--
-- Name: tracked_keywords uk_tracked_keywords_keyword; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tracked_keywords
    ADD CONSTRAINT uk_tracked_keywords_keyword UNIQUE (keyword);

--
-- Name: vector_store vector_store_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.vector_store
    ADD CONSTRAINT vector_store_pkey PRIMARY KEY (id);

--
-- Name: idx_accounts_status; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_accounts_status ON public.accounts USING btree (status);

--
-- Name: idx_comment_like_account_comment; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_comment_like_account_comment ON public.comment_like USING btree (account_id, comment_id);

--
-- Name: idx_comments_parent_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_comments_parent_id ON public.comments USING btree (parent_id);

--
-- Name: idx_comments_post_created_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_comments_post_created_at ON public.comments USING btree (post_id, created_at);

--
-- Name: idx_post_file_post_created_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_post_file_post_created_at ON public.post_file USING btree (post_id, created_at);

--
-- Name: idx_post_like_account_post; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_post_like_account_post ON public.post_like USING btree (account_id, post_id);

--
-- Name: idx_post_reference_links_post_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_post_reference_links_post_id ON public.post_reference_links USING btree (post_id);

--
-- Name: idx_post_reference_links_provider; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_post_reference_links_provider ON public.post_reference_links USING btree (provider);

--
-- Name: idx_post_tags_post_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_post_tags_post_id ON public.post_tags USING btree (post_id);

--
-- Name: idx_posts_account_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_posts_account_id ON public.posts USING btree (account_id);

--
-- Name: idx_posts_board_category; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_posts_board_category ON public.posts USING btree (board_category);

--
-- Name: idx_posts_category; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_posts_category ON public.posts USING btree (category);

--
-- Name: idx_posts_created_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_posts_created_at ON public.posts USING btree (created_at);

--
-- Name: idx_posts_publish_origin; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_posts_publish_origin ON public.posts USING btree (publish_origin);

--
-- Name: spring_ai_vector_index; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX spring_ai_vector_index ON public.vector_store USING hnsw (embedding public.vector_cosine_ops);

--
-- Name: account_roles fk61h48dsir3h82pxbq3cwgp0ce; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.account_roles
    ADD CONSTRAINT fk61h48dsir3h82pxbq3cwgp0ce FOREIGN KEY (account_id) REFERENCES public.accounts(id);

--
-- Name: post_reference_links fkanh041l5gmwvo5icwdje66yxk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.post_reference_links
    ADD CONSTRAINT fkanh041l5gmwvo5icwdje66yxk FOREIGN KEY (post_id) REFERENCES public.posts(id) ON DELETE CASCADE;

--
-- Name: post_like fkcf8kqsucxsmplv3xw9gubrql0; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.post_like
    ADD CONSTRAINT fkcf8kqsucxsmplv3xw9gubrql0 FOREIGN KEY (post_id) REFERENCES public.posts(id) ON DELETE CASCADE;

--
-- Name: comments fkh4c7lvsc298whoyd4w9ta25cr; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.comments
    ADD CONSTRAINT fkh4c7lvsc298whoyd4w9ta25cr FOREIGN KEY (post_id) REFERENCES public.posts(id) ON DELETE CASCADE;

--
-- Name: post_file fkk08pgr1gtb7sg0dpsh6pdinc; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.post_file
    ADD CONSTRAINT fkk08pgr1gtb7sg0dpsh6pdinc FOREIGN KEY (post_id) REFERENCES public.posts(id);

--
-- Name: post_tags fkkifam22p4s1nm3bkmp1igcn5w; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.post_tags
    ADD CONSTRAINT fkkifam22p4s1nm3bkmp1igcn5w FOREIGN KEY (post_id) REFERENCES public.posts(id);

--
-- Name: comment_like fkl1mu2ryf4k4ps93b5b52q2m8i; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.comment_like
    ADD CONSTRAINT fkl1mu2ryf4k4ps93b5b52q2m8i FOREIGN KEY (comment_id) REFERENCES public.comments(id) ON DELETE CASCADE;

--
-- Name: comments fklri30okf66phtcgbe5pok7cc0; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.comments
    ADD CONSTRAINT fklri30okf66phtcgbe5pok7cc0 FOREIGN KEY (parent_id) REFERENCES public.comments(id) ON DELETE CASCADE;

--
-- PostgreSQL database dump complete
--
