-- Owner: study
-- Purpose: 사용자가 올린 자료로 학습하는 기능의 테이블을 만든다.
--          자료(study_sources), 근거가 검증된 복습 문제(study_questions), 덧붙이기만 하는 학습 기록(study_records).
-- Tables: study_sources, study_questions, study_records
-- Compatibility: 새 테이블만 만든다. 기존 테이블은 바꾸지 않는다.
-- Rollback: DROP TABLE study_records; DROP TABLE study_questions; DROP TABLE study_sources;
-- Verification: 빈 DB에 적용한 뒤 ddl-auto=validate로 기동되고,
--               없는 account_id로 study_sources INSERT가 FK 위반으로 실패한다.

CREATE TABLE study_sources (
    id                       bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_account_id         bigint                         NOT NULL REFERENCES accounts (id),
    title                    character varying(100)         NOT NULL,
    content                  character varying(20000)       NOT NULL,
    question_status          character varying(20)          NOT NULL
        CONSTRAINT study_sources_question_status_check CHECK (question_status IN ('GENERATING', 'READY')),
    discarded_question_count integer                        NOT NULL,
    created_at               timestamp(6) without time zone NOT NULL
);

CREATE INDEX idx_study_sources_owner ON study_sources (owner_account_id, id DESC);

CREATE TABLE study_questions (
    id               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_id        bigint                         NOT NULL REFERENCES study_sources (id),
    owner_account_id bigint                         NOT NULL REFERENCES accounts (id),
    question         character varying(500)         NOT NULL,
    evidence         character varying(1000)        NOT NULL,
    origin           character varying(10)          NOT NULL
        CONSTRAINT study_questions_origin_check CHECK (origin IN ('LLM', 'RULE', 'USER')),
    box              integer                        NOT NULL,
    due_at           timestamp(6) without time zone NOT NULL,
    version          bigint                         NOT NULL,
    created_at       timestamp(6) without time zone NOT NULL
);

-- 오늘 할 것: 내 문제 중 due_at이 지난 것을 due_at 순으로 읽는다.
CREATE INDEX idx_study_questions_owner_due ON study_questions (owner_account_id, due_at);
CREATE INDEX idx_study_questions_source ON study_questions (source_id);

CREATE TABLE study_records (
    id               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_account_id bigint                         NOT NULL REFERENCES accounts (id),
    source_id        bigint                         NOT NULL REFERENCES study_sources (id),
    source_title     character varying(100)         NOT NULL,
    question_id      bigint REFERENCES study_questions (id),
    kind             character varying(20)          NOT NULL
        CONSTRAINT study_records_kind_check CHECK (kind IN ('ANSWER', 'RECALL', 'TEACH', 'QUESTION')),
    prompt           character varying(500),
    user_text        character varying(10000),
    result           character varying(2000),
    created_at       timestamp(6) without time zone NOT NULL
);

CREATE INDEX idx_study_records_owner ON study_records (owner_account_id, id DESC);
