#!/usr/bin/env bash

# Shared test-tool environment loader.
# This file is meant to be sourced by setup shell entrypoints.

tests_env_path() {
  local root_dir="$1"
  printf '%s/tests/.env' "$root_dir"
}

tests_gitignore_path() {
  local root_dir="$1"
  printf '%s/tests/.gitignore' "$root_dir"
}

write_tests_gitignore_block() {
  cat <<'EOF'
# >>> setup local test artifacts >>>
# Local env/secrets and tool caches generated by setup.
.env
.env.*
*.local
bruno/api/.env
bruno/api/environments/local.bru
bruno/api/node_modules/
k6/results/
k6/*.summary.json
# <<< setup local test artifacts <<<
EOF
}

ensure_tests_gitignore() {
  local root_dir="$1"
  local gitignore_path
  gitignore_path="$(tests_gitignore_path "$root_dir")"

  mkdir -p "$(dirname "$gitignore_path")"

  if [[ ! -f "$gitignore_path" ]]; then
    write_tests_gitignore_block > "$gitignore_path"
    printf '[env] created %s\n' "${gitignore_path#$root_dir/}"
    return
  fi

  if ! grep -q '# >>> setup local test artifacts >>>' "$gitignore_path" 2>/dev/null; then
    {
      printf '\n'
      write_tests_gitignore_block
    } >> "$gitignore_path"
    printf '[env] updated %s\n' "${gitignore_path#$root_dir/}"
  fi
}

write_default_tests_env() {
  local env_path="$1"

  mkdir -p "$(dirname "$env_path")"
  cat > "$env_path" <<'EOF'
# Local test-tool settings.
# This file is generated by setup and protected by tests/.gitignore.
# Leave a value empty to let setup or the tool script use its built-in default.
#
# Do not paste long-lived production secrets here. Prefer short-lived local
# credentials or pass sensitive values as one-off shell env variables.

# Shared target
BASE_URL=http://localhost:8080
SMOKE_PATH=/

# Bruno smoke runtime
BRUNO_VERBOSE=false
BRUNO_FILTER_TAGS=smoke
BRUNO_EXCLUDE_TAGS=draft,scenario,requires-review

# k6 runtime
K6_SCRIPT_ROOT=tests/k6
K6_REPORT_ROOT=setup/reports/k6
K6_TARGET_NAME=local
K6_SCENARIO_NAME=
K6_REPORT_NAME=
K6_REPORT_DIR=
K6_SUMMARY_DIR=
K6_RUN_ID=
K6_TEE_LOG=true
VUS_COUNT=1
ITERATIONS=1
PUBLIC_VUS=
TEST_SECONDS=

# Optional local-only credentials for manual scenarios
PERF_USER_ID=
PERF_PASSWORD=
PERF_ACCESS_TOKEN=
PERF_AUTH_HEADER=
INTERNAL_API_KEY=
COLLECTOR_INTERNAL_API_KEY=

# Optional tool version/path overrides
BRUNO_CLI_VERSION=
K6_VERSION=
K6_BIN=
K6_BIN_DIR=

# Install policy. Default is user-local; system installs must be explicit.
# Valid values: user, system
SETUP_INSTALL_MODE=user
BRUNO_INSTALL_MODE=
K6_INSTALL_MODE=
EOF
}

ensure_tests_env() {
  local root_dir="$1"
  local env_path
  env_path="$(tests_env_path "$root_dir")"

  if [[ -f "$env_path" ]]; then
    return
  fi

  write_default_tests_env "$env_path"
  printf '[env] created %s\n' "${env_path#$root_dir/}"
}

strip_env_quotes() {
  local value="$1"

  if [[ "$value" == \"*\" && "$value" == *\" ]]; then
    value="${value:1:${#value}-2}"
  elif [[ "$value" == \'*\' && "$value" == *\' ]]; then
    value="${value:1:${#value}-2}"
  fi

  printf '%s' "$value"
}

load_tests_env() {
  local root_dir="$1"
  local env_path
  env_path="$(tests_env_path "$root_dir")"

  ensure_tests_gitignore "$root_dir"
  ensure_tests_env "$root_dir"

  local line key value
  while IFS= read -r line || [[ -n "$line" ]]; do
    line="${line%$'\r'}"
    [[ -z "$line" || "$line" == \#* ]] && continue
    [[ "$line" == *"="* ]] || continue

    key="${line%%=*}"
    value="${line#*=}"

    [[ "$key" =~ ^[A-Za-z_][A-Za-z0-9_]*$ ]] || continue

    value="$(strip_env_quotes "$value")"

    # Shell-provided values win over tests/.env. Empty values are still loaded,
    # letting downstream ${VAR:-default} and k6 env helpers fall back.
    if [[ -z "${!key+x}" ]]; then
      export "$key=$value"
    fi
  done < "$env_path"
}
