management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus
  endpoint:
    prometheus:
      access: read-only
  metrics:
    tags:
      application: postforge
    distribution:
      percentiles-histogram:
        http.server.requests: true
        external_source_fetch: true
        external_source_db_persist: true
        external_naver_fetch: true
        ai_text_generation: true
      slo:
        http.server.requests: 100ms,300ms,500ms,1s,2s
        external_source_fetch: 100ms,300ms,500ms,1s,2s,5s
        external_source_db_persist: 100ms,300ms,500ms,1s,2s,5s
        external_naver_fetch: 100ms,300ms,500ms,1s,2s,5s
        ai_text_generation: 500ms,1s,2s,5s,10s,30s

monitoring:
  username: ${MONITORING_USERNAME}
  password: ${MONITORING_PASSWORD}
