### 1. 로컬 파일 업로드 (POST)
POST http://localhost:8080/files/local/upload
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="my_test_image.png"
Content-Type: image/png

< C:/SpringWorkspace/post-forge/board/src/test/resources/sample.png
--WebAppBoundary--

### 2-1. 로컬 파일 조회 (GET)
GET http://localhost:8080/files/local/download/1?download=false

### 2-2. 로컬 파일 다운로드 (GET)
GET http://localhost:8080/files/local/download/1?download=true

### 3. S3 presigned URL 발급 (업로드용)
GET http://localhost:8080/files/s3/presigned-url?fileName=sample.png&contentType=image/png

> {%
client.global.set("presignedUrl", response.body.url);
client.global.set("s3FileId", response.body.fileId);
%}

### 3-1. presigned URL로 S3에 직접 업로드
PUT {{presignedUrl}}
Content-Type: image/png

< F:\01_Dev Project\01_Spring\001_Post Forge_v1.0\board\src\test\resources\sample.png

### 4. S3 다운로드 URL 발급
GET http://localhost:8080/files/s3/{{s3FileId}}/download-url