FROM gradle:8.10-jdk21 AS build

WORKDIR /workspace

COPY . .

RUN gradle clean :app:bootJar -x test --no-daemon

FROM eclipse-temurin:21-jre AS runtime

WORKDIR /app

COPY --from=build /workspace/app/build/libs/app.jar app.jar

EXPOSE 8080

ENTRYPOINT ["java", "-jar", "app.jar"]
