server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postforge
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false