-- Owner: source, ingest, catalog, price, board
-- Purpose: Add external product collection, normalized catalog, price snapshot/read-model, and product-post link tables.
-- Tables: source_policies, external_api_request_logs, tracked_keywords, collection_jobs, raw_products, product_categories, products, offers, product_embeddings, product_match_candidates, price_snapshots, lowest_price_snapshots, auto_post_drafts, post_product_links
-- Compatibility: Additive table creation. Existing auth/board/ai rows are not changed.
-- Rollback: DROP TABLE IF EXISTS post_product_links, auto_post_drafts, lowest_price_snapshots, price_snapshots, product_match_candidates, product_embeddings, offers, raw_products, collection_jobs, tracked_keywords, products, product_categories, external_api_request_logs, source_policies;
-- Verification: Compare with source, ingest, catalog, price, and board JPA entities; run bash gradlew :source:test :catalog:test :price:test :ingest:test :board:test :app:compileJava.

CREATE EXTENSION IF NOT EXISTS vector;

CREATE TABLE IF NOT EXISTS source_policies (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source VARCHAR(30) NOT NULL,
    enabled BOOLEAN NOT NULL,
    daily_quota INTEGER NOT NULL,
    max_retry_attempts INTEGER NOT NULL,
    circuit_failure_threshold INTEGER NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT uk_source_policies_source UNIQUE (source)
);

CREATE TABLE IF NOT EXISTS external_api_request_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source VARCHAR(30) NOT NULL,
    endpoint VARCHAR(200) NOT NULL,
    request_key VARCHAR(200) NOT NULL,
    status_code INTEGER,
    success BOOLEAN NOT NULL,
    response_time_ms BIGINT NOT NULL,
    error_message VARCHAR(1000),
    requested_at TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS tracked_keywords (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    keyword VARCHAR(100) NOT NULL,
    source VARCHAR(30) NOT NULL,
    interval_minutes INTEGER NOT NULL,
    display_count INTEGER NOT NULL,
    enabled BOOLEAN NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT uk_tracked_keywords_source_keyword UNIQUE (source, keyword)
);

CREATE TABLE IF NOT EXISTS collection_jobs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tracked_keyword_id BIGINT,
    source VARCHAR(30) NOT NULL,
    keyword VARCHAR(100) NOT NULL,
    status VARCHAR(30) NOT NULL,
    requested_at TIMESTAMP NOT NULL,
    started_at TIMESTAMP,
    finished_at TIMESTAMP,
    collected_count INTEGER NOT NULL DEFAULT 0,
    failure_reason VARCHAR(1000),
    retry_count INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS raw_products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    collection_job_id BIGINT NOT NULL REFERENCES collection_jobs(id),
    source VARCHAR(30) NOT NULL,
    external_product_id VARCHAR(120) NOT NULL,
    raw_payload TEXT NOT NULL,
    collected_at TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS product_categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE,
    parent_id BIGINT,
    depth INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source VARCHAR(30) NOT NULL,
    external_product_id VARCHAR(120) NOT NULL,
    name VARCHAR(200) NOT NULL,
    normalized_name VARCHAR(200) NOT NULL,
    brand VARCHAR(100),
    maker VARCHAR(100),
    category_id BIGINT REFERENCES product_categories(id),
    category1 VARCHAR(100),
    category2 VARCHAR(100),
    category3 VARCHAR(100),
    current_price BIGINT NOT NULL,
    image_url VARCHAR(1000),
    product_url VARCHAR(1000),
    mall_name VARCHAR(100),
    status VARCHAR(30) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT uk_products_source_external_id UNIQUE (source, external_product_id)
);

CREATE INDEX IF NOT EXISTS idx_products_normalized_name ON products(normalized_name);
CREATE INDEX IF NOT EXISTS idx_products_category_id ON products(category_id);
CREATE INDEX IF NOT EXISTS idx_products_status_created_at ON products(status, created_at);

CREATE TABLE IF NOT EXISTS offers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT NOT NULL REFERENCES products(id),
    source VARCHAR(30) NOT NULL,
    external_product_id VARCHAR(120) NOT NULL,
    mall_name VARCHAR(100),
    title VARCHAR(200) NOT NULL,
    product_url VARCHAR(1000),
    image_url VARCHAR(1000),
    active BOOLEAN NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT uk_offers_source_external_product_id UNIQUE (source, external_product_id)
);

CREATE INDEX IF NOT EXISTS idx_offers_product_id ON offers(product_id);

CREATE TABLE IF NOT EXISTS product_embeddings (
    product_id BIGINT PRIMARY KEY REFERENCES products(id),
    embedding_input TEXT NOT NULL,
    embedding VECTOR(1536) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_product_embeddings_embedding
    ON product_embeddings USING hnsw (embedding vector_cosine_ops);

CREATE TABLE IF NOT EXISTS product_match_candidates (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_product_id BIGINT NOT NULL,
    source VARCHAR(30) NOT NULL,
    external_product_id VARCHAR(120) NOT NULL,
    source_product_title VARCHAR(200) NOT NULL,
    candidate_product_id BIGINT NOT NULL,
    similarity_score NUMERIC(6, 4) NOT NULL,
    brand_matched BOOLEAN NOT NULL,
    category_matched BOOLEAN NOT NULL,
    status VARCHAR(30) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT uk_product_match_candidates_source_candidate_status UNIQUE (
        source_product_id,
        candidate_product_id,
        status
    )
);

CREATE INDEX IF NOT EXISTS idx_product_match_candidates_status_created
    ON product_match_candidates(status, created_at);

CREATE INDEX IF NOT EXISTS idx_product_match_candidates_candidate
    ON product_match_candidates(candidate_product_id);

CREATE TABLE IF NOT EXISTS price_snapshots (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT NOT NULL,
    offer_id BIGINT NOT NULL,
    source VARCHAR(30) NOT NULL,
    external_product_id VARCHAR(120) NOT NULL,
    price BIGINT NOT NULL,
    collected_at TIMESTAMP NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_price_snapshots_product_collected
    ON price_snapshots(product_id, collected_at);

CREATE INDEX IF NOT EXISTS idx_price_snapshots_offer_collected
    ON price_snapshots(offer_id, collected_at);

CREATE INDEX IF NOT EXISTS idx_price_snapshots_source_external
    ON price_snapshots(source, external_product_id);

CREATE TABLE IF NOT EXISTS lowest_price_snapshots (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT NOT NULL,
    offer_id BIGINT NOT NULL,
    source VARCHAR(30) NOT NULL,
    external_product_id VARCHAR(120) NOT NULL,
    lowest_price BIGINT NOT NULL,
    previous_lowest_price BIGINT,
    drop_rate NUMERIC(8, 2),
    changed_at TIMESTAMP NOT NULL,
    collected_at TIMESTAMP NOT NULL,
    CONSTRAINT uk_lowest_price_snapshots_product UNIQUE (product_id)
);

CREATE INDEX IF NOT EXISTS idx_lowest_price_snapshots_drop_rate
    ON lowest_price_snapshots(drop_rate);

CREATE TABLE IF NOT EXISTS auto_post_drafts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT NOT NULL,
    event_id VARCHAR(80) NOT NULL,
    title VARCHAR(100) NOT NULL,
    content VARCHAR(10000) NOT NULL,
    status VARCHAR(30) NOT NULL,
    post_id BIGINT REFERENCES posts(id),
    created_at TIMESTAMP NOT NULL,
    published_at TIMESTAMP,
    CONSTRAINT uk_auto_post_drafts_event_id UNIQUE (event_id)
);

CREATE INDEX IF NOT EXISTS idx_auto_post_drafts_product_created
    ON auto_post_drafts(product_id, created_at);

CREATE INDEX IF NOT EXISTS idx_auto_post_drafts_status_created
    ON auto_post_drafts(status, created_at);

CREATE TABLE IF NOT EXISTS post_product_links (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id BIGINT NOT NULL REFERENCES posts(id),
    product_id BIGINT NOT NULL,
    post_date DATE NOT NULL,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT uk_post_product_links_post_id UNIQUE (post_id),
    CONSTRAINT uk_post_product_links_product_post_date UNIQUE (product_id, post_date)
);

CREATE INDEX IF NOT EXISTS idx_post_product_links_product_id ON post_product_links(product_id);
