name: master 워크플로우
on:
  push:
    branches: [ 'master' ]

env:
  SPRING_PROFILE: prod

jobs:
  prepare-variables:
    name: 환경변수 준비하기
    runs-on: ubuntu-latest
    outputs:
      image-tag: ${{ steps.setup-env.outputs.image-tag }}
      spring-profile: ${{ steps.setup-env.outputs.spring-profile }}
    steps:
      - name: GitHub 에서 레포 받아오기
        uses: actions/checkout@v3

      - name: 환경변수 출력하기
        id: setup-env
        run: |
          echo "image-tag=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
          echo "spring-profile=$SPRING_PROFILE" >> $GITHUB_OUTPUT

  call-build-workflow:
    if: github.event_name == 'push'
    needs: [ prepare-variables ]
    name: 이미지 빌드
    uses: ./.github/workflows/build-dockerhub.yaml
    permissions:
      id-token: write
      contents: read
    with:
      image-name: cchuyong/login-api
      image-tag: ${{ needs.prepare-variables.outputs.image-tag }}
      spring-profile: ${{ needs.prepare-variables.outputs.spring-profile }}
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
